name: Release extension
on:
  release:
    types: [published]

jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # setup
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      # bump version number
      - name: Version bump
        run: npm version from-git --no-git-tag-version
        continue-on-error: true
      - name: Version sync
        run: npx version-everything manifest.json
        continue-on-error: true
      # build extension
      - run: npm run build
      # pack zip
      - run: mkdir hosted
      - name: Pack
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: dist
          zipFilePath: hosted/extension.zip
      # convert zip to Firefox xpi
      - name: Create .xpi
        uses: cardinalby/webext-buildtools-firefox-sign-xpi-action@v1
        with:
          timeoutMs: 600000
          zipFilePath: hosted/extension.zip
          xpiFilePath: hosted/extension.xpi
          jwtIssuer: ${{ secrets.MOZILLA_JWT_ISSUER }}
          jwtSecret: ${{ secrets.MOZILLA_JWT_SECRET }}
          extensionId: digitaleksamen@jfagerberg.me
          channel: unlisted
      # publish to the release
      - name: Release .xpi
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: hosted/extension.xpi
          asset_name: digitaleksamen_enhancer.xpi
          asset_content_type: application/x-xpinstall
      - name: Release .zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: hosted/extension.zip
          asset_name: digitaleksamen_enhancer.zip
          asset_content_type: application/zip
